
package texteditor;

/*
 * Copyright (C) 2017 Dheeraj Kumar Pant
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
     * version 0.10 13 Jan 2017 @author Dheeraj Kumar Pant.
     * 
     * This class is designed to make a set of keys from one key input by user.
     * Class contains two public constructors one with argument that is key input by user and other is general constructor.
     * Class have 5 private longeger variables 
     * The class contains a number of private methods with return type longeger
     * generateKey1(longeger variable)
     * geerateKey2(longeger variable, longeger variable)
     * generateKey3(longeger variable, longeger variable, longeger variable)
     * generateKey4(longeger variable, longeger variable, longeger variable, longeger variable)
     * digitAdder(longeger variable)
     * digitAdderInPair(longeger variable)
     * mod256(longeger variable)
     * valueShiftLeft(longeger variable, longeger variable)
     * 
     * The class contains two default method with return type longeger array
     * getKeySet(longeger variable)
     * getKeySet()
*/

public class KeyGenerator {

    /**
     *  key: This variable contains key given by user
     */
    private long key;
    
    /**
     * key1: This variable contains 8 bit key generated by algorithm
     */
    private long key1;
    
    /**
     * key2: This variable contains 32 bit key generated by algorithm
     */
    private long key2;
    
    /**
     * key3: This variable contains 32 bit key generated by algorithm
     */
    private long key3;
    
    /**
     * key4: This variable contains 32 bit key generated by algorithm
     */
    private long key4;
    
    /**
     * The class contains one constant MAX_MOD that contains value 256 that is used in mod.
     */
    public static final long MAX_MOD=256;
    
    /**
    *Constructor taking an argument that is key.
    */
    public KeyGenerator(long key)
    {
        this.key=key;
    }
    
    /**
    *General constructor.
    */
    public KeyGenerator()
    {
        
    }
    
    /**
    *getKeySet(longeger variable) returns a set of keys generated from the argument key.
    *An longeger array is declared in the function.
    *Four functions are called and assigned key values to array.
    */
    long[] getKeySet(long key)
    {
        long[] key_set=new long[4];
        
        key1=generateKey1(key);
        key2=generateKey2(key,key1);
        key3=generateKey3(key,key1,key2);
        key4=generateKey4(key,key1,key2,key3);
        
        key_set[0]=key1;
        key_set[1]=key2;
        key_set[2]=key3;
        key_set[3]=key4;
        
        return key_set;
    }
    
    /**
    *getKeySet() returns a set of keys.
    *An longeger array is declared in the function.
    *Four functions are called and assigned key values to array.
    */
    long[] getKeySet()
    {
        long[] key_set=new long[4];
        
        key1=generateKey1(key);
        key2=generateKey2(key,key1);
        key3=generateKey3(key,key1,key2);
        key4=generateKey4(key,key1,key2,key3);
        
        key_set[0]=key1;
        key_set[1]=key2;
        key_set[2]=key3;
        key_set[3]=key4;
        
        return key_set;
    }
    
    /**
    * Function Name: generateKey1(longeger variabe)
    * Variables Used: longeger key1
    *This function is used to generate key1 from the key given in argument.
    *All the digits of key are added using digitAdder() function.
    *Then argument key is rotated left using Integer.rotateLeft() funnction by the result of digitAdder() function.
    *The resultant key is key1 returned.
    */
    private long generateKey1(long key) 
    {
        long key1 = Long.rotateLeft(key, (int)this.digitAdder(key));
        return key1;
    }

    /**
    * Function Name: generateKey2(longeger variable, longeger variable)
    * Variables Used: longeger key2
    *This function is used to generate key2.
    *firstly XOR of key and key1 is stored in key2 variable.
    *Then key2 is reversed.
    *Then to get 8 bit output digitdderInPair() function is used.
    *The result of function call is key2
    */
    private long generateKey2(long key, long key1) 
    {
        long key2 = key ^ key1;
        
        key2 = this.reverseValue(key2);
        key2 = this.digitAdderInPair(key2);
        
        return key2;
    }

    /**
    * Function Name: generateKey3(longeger variable,longeger variable,longeger variable)
    * Variables Used: longeger key3
    *This function performs operations and return key3 by using argument keys.
    */
    private long generateKey3(long key, long key1, long key2) 
    {
        key1 = key ^ key1;
        key1 = this.reverseValue(key1);
        
        long key3 = this.digitAdderInPair(key1);
        
        key3 = this.reverseValue(key3);
        key3 ^= key2;
        key3 = this.mod256(key3);
        
        return key3;
    }

    /**
    * Function Name: generateKey4(longeger variable, longeger variable, longeger variable, longeger variable)
    * Variables Used: longeger key4
    */
    private long generateKey4(long key, long key1, long key2, long key3) 
    {
        key = Long.rotateLeft(key, (int)this.digitAdder(key2));
        key1 = Long.rotateLeft(key1, (int)this.digitAdder(key3));
        
        long key4 = this.reverseValue(key);
        
        key4 ^= key1;
        key4 ^= key;
        key4 = this.reverseValue(key4);
        
        return key4;
    }

    /**
    Function Name: digitAdder(long x)
    This function add all digits of given number.
    */
    private long digitAdder(long x) {
        if (x < 0) {
            x *= -1;
        }
        while (x > 9) {
            String s = "" + x;
            long y = 0;
            for (long i = 0; i < s.length(); ++i) {
                y += Long.parseLong(s.substring((int)i, (int)(i + 1)));
            }
            x = y;
        }
        return x;
    }

    /**
    Function Name: digitAdderInPair(long Val)
    This function add digits of given number in pair of 3.
    */
    private long digitAdderInPair(long val) 
    {
        StringBuffer s = new StringBuffer("" + val);
        String[] sr = new String[5];
        long len = s.length();
        long add_need = 10 - len;
        StringBuffer s2 = new StringBuffer();
        
        for (long i = 0; i < add_need; ++i) 
        {
            s2 = s2.append("0");
        }
        
        s2 = s2.append(s);
        long j = 0;
        
        for (long i2 = 0; i2 < 5; ++i2) 
        {
            sr[(int)i2] = ""+this.digitAdder(Long.parseLong(s2.substring((int)j, (int)(j + 2))));
            j += 2;
        }
        
        sr[2] = sr[0] + sr[1] + sr[2];
        sr[2] = "" + this.digitAdder(Integer.parseInt(sr[2]));
        sr[2] = sr[2] + sr[3] + sr[4];
        long x = Integer.parseInt(sr[2]);
        x = this.mod256(x);
        
        return x;
    }

    /**
    Function Name: mod256(long num)
    This function calculate mod of a given number.
    */
    private long mod256(long num)
    {
        long num_mod=num;
        
        if(num<MAX_MOD)
        {
            return num_mod;
        }
        else
        {
            while(num_mod>MAX_MOD)
            {
                num_mod=num_mod-MAX_MOD;
            }
        }
        
        return num_mod;
    }
    
    /**
    Function Name: reverseValue(long val)
    This function reverse the given number.
    */
    private long reverseValue(long val) 
    {
        long x = val;
        boolean flag = false;
        StringBuffer s = new StringBuffer(""+x);
        if (s.toString().contains("-"))
        {
            s = s.deleteCharAt(s.indexOf("-"));
            flag = true;
        }
        s = s.reverse();
        
        x = Long.parseLong(s.toString());
        if (flag)
            x *=-1;
        
        return x;
    }
    
    /**
    Function Name: valueShiftLeft(long val, long shift)
    This function shift the bits of given number.
    */
    private  long valueShiftLeft(long val, long shift)
    {
        String s = "" + val;
        char[] c = s.toCharArray();
        
        if (shift != 0) {
            if (s.length() == 3) 
            {
                for (long i = 0; i < shift; ++i)
                {
                    char tmp1 = c[2];
                    char tmp2 = c[1];
                    c[1] = c[0];
                    c[2] = tmp2;
                    c[0] = tmp1;
                }
                s = "" + c[0] + c[1] + c[2];
            }
            else if (s.length() == 2) 
            {
                for (long i = 0; i < shift; ++i)
                {
                    char tmp1 = c[1];
                    c[1] = c[0];
                    c[0] = tmp1;
                }
                
                s = "" + c[0] + c[1];
            } 
            else if (s.length() == 1) 
            {
                return val;
            }
        }
        
        val = Long.parseLong(s);
        
        return val;
    }


}

